import { Inter, Concert_One } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const concertOne = Concert_One({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-concert-one",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script
          data-no-cookie
          async
          src="https://cdn.splitbee.io/sb.js"
        ></script>
      </head>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          inter.variable,
          concertOne.variable
        )}
      >
        {children}
      </body>
    </html>
  );
}
